-- Generate Treesitter syntax highlighting for LOVE functions

local api = require 'love-api.love_api'

local scm_modules = {}
local scm_types = {}
local scm_callbacks = {}

local function extractData(tab, path)
    path = path or ''

    for i, v in pairs(tab) do
        if i == 'functions' then
            if tab.name and (tab.name or ''):sub(1, 1):match('%l') then
                if not scm_modules[tab.name] then
                    scm_modules[tab.name] = {}
                end
                for _, func in pairs(v) do
                    table.insert(scm_modules[tab.name], func.name)
                end
            else
                for _, func in pairs(v) do
                    table.insert(scm_types, func.name)
                end
            end
        elseif i == 'callbacks' then
            for _, callback in pairs(v) do
                table.insert(scm_callbacks, callback.name)
            end
        end

        if type(v) == 'table' then
            extractData(v, path .. (tab.name and (tab.name .. '.') or ''))
        end
    end
end

extractData(api)

local scm_types_str = ''
local scm_callbacks_str = ''
local scm_modules_str = ''

for _, typ in ipairs(scm_types) do
    scm_types_str = scm_types_str .. typ .. '|'
end

for _, callback in ipairs(scm_callbacks) do
    scm_callbacks_str = scm_callbacks_str .. callback .. '|'
end

for module_name, _ in pairs(scm_modules) do
    scm_modules_str = scm_modules_str .. module_name .. '|'
end

if scm_types_str ~= '' then
    scm_types_str = scm_types_str:sub(1, -2)
end

if scm_callbacks_str ~= '' then
    scm_callbacks_str = scm_callbacks_str:sub(1, -2)
end

if scm_modules_str ~= '' then
    scm_modules_str = scm_modules_str:sub(1, -2)
end

local scm_content = [[
; extends

; LOVE framework highlighting for Treesitter

; WARNING!
; Do not edit this file!
; It's generated by `src/syntax/lua/treesitter.lua`
; If you want to change the syntax, edit that file and run `src/gen.dat(sh)`
; it to generate a new version of this file.

]]

scm_content = scm_content
    .. '((dot_index_expression\n'
    .. '  table: (identifier) @variable.global.love)\n'
    .. '  (#eq? @variable.global.love "love"))\n\n'
    .. '; Modules\n'
    .. '((dot_index_expression\n'
    .. '  table: (identifier) @_love\n'
    .. '  field: (identifier) @module.love)\n'
    .. '  (#eq? @_love "love")\n'
    .. '  (#match? @module.love\n'
    .. '    "^(' .. scm_modules_str .. ')$"))\n\n'
    .. '; Functions\n'
for module_name, functions in pairs(scm_modules) do
    local funcs_str = ''
    for _, func in ipairs(functions) do
        funcs_str = funcs_str .. func .. '|'
    end
    if funcs_str ~= '' then
        funcs_str = funcs_str:sub(1, -2)
        scm_content = scm_content
            .. '((dot_index_expression\n'
            .. '  table: (dot_index_expression\n'
            .. '    table: (identifier) @_love\n'
            .. '    field: (identifier) @_module)\n'
            .. '  field: (identifier) @function.love)\n'
            .. '  (#eq? @_love "love")\n'
            .. '  (#eq? @_module "' .. module_name .. '")\n'
            .. '  (#match? @function.love\n'
            .. '    "^(' .. funcs_str .. ')$"))\n\n'
    end
end

if scm_types_str ~= '' then
    scm_content = scm_content
        .. '; Types\n'
        .. '((dot_index_expression\n'
        .. '  table: (identifier) @_love\n'
        .. '  field: (identifier) @type.love)\n'
        .. '  (#eq? @_love "love")\n'
        .. '  (#match? @type.love\n'
        .. '    "^(' .. scm_types_str .. ')$"))\n\n'
end

if scm_callbacks_str ~= '' then
    scm_content = scm_content
        .. '; Callbacks\n'
        .. '((dot_index_expression\n'
        .. '  table: (identifier) @_love\n'
        .. '  field: (identifier) @function.love.callback)\n'
        .. '  (#eq? @_love "love")\n'
        .. '  (#match? @function.love.callback\n'
        .. '    "^(' .. scm_callbacks_str .. ')$"))\n'
end

print(scm_content)
